apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  availability: QRIScloud
provisioner: cinder.csi.openstack.org
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-qriscloud-retain
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  availability: QRIScloud
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-qriscloud-delete
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  availability: QRIScloud
