apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  availability: melbourne-qh2
provisioner: cinder.csi.openstack.org
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-jupyterhub-retain
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  availability: melbourne-qh2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-jupyterhub-delete
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  availability: melbourne-qh2
